package com.example.waterpotabilityapp.view
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0A1D28)
val md_theme_light_onPrimary = Color(0xFFD7F5F0)
val md_theme_light_primaryContainer = Color(0xFF0B524F)
val md_theme_light_onPrimaryContainer = Color(0xFF02091E)
val md_theme_light_secondary = Color(0xFFCFD4DA)
val md_theme_light_onSecondary = Color(0xFFFFFEFE)
val md_theme_light_secondaryContainer = Color(0xFF2F01AF)
val md_theme_light_onSecondaryContainer = Color(0xFF041527)
val md_theme_light_tertiary = Color(0xFF6ADE95)
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_tertiaryContainer = Color(0xFFBBCBEA)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFEFF)
val md_theme_light_error = Color(0xFFBAD3E7)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF002C41)
val md_theme_light_background = Color(0xFF3D8AA8)
val md_theme_light_onBackground = Color(0xFF091B23)
val md_theme_light_surface = Color(0xFFECFAFA)
val md_theme_light_onSurface = Color(0xFF16171F)
val md_theme_light_surfaceVariant = Color(0xFFCCFCFF)
val md_theme_light_onSurfaceVariant = Color(0xFF0A1A28)
val md_theme_light_outline = Color(0xFF0E1428)
val md_theme_light_inverseOnSurface = Color(0xFF222B2B)
val md_theme_light_inverseSurface = Color(0xFFEBF8FF)
val md_theme_light_inversePrimary = Color(0xFF51C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFFFFFF)
val md_theme_light_outlineVariant = Color(0xFF0277BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF494C53)
val md_theme_dark_onPrimary = Color(0x9C0A1A21)
val md_theme_dark_primaryContainer = Color(0xFFAEE5E3)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_secondary = Color(0xFFFFFFFF)
val md_theme_dark_onSecondary = Color(0xFF57D7D7)
val md_theme_dark_secondaryContainer = Color(0xFF585865)
val md_theme_dark_onSecondaryContainer = Color(0xFF253844)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFFCFE2C0)
val md_theme_dark_tertiaryContainer = Color(0xFFBDFF8C)
val md_theme_dark_onTertiaryContainer = Color(0xFF34392D)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF170607)
val md_theme_dark_onError = Color(0xFF004869)
val md_theme_dark_onErrorContainer = Color(0xFFD6FFDB)
val md_theme_dark_background = Color(0xCE030F15)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF000000)
val md_theme_dark_onSurface = Color(0xFFB5B8BF)
val md_theme_dark_surfaceVariant = Color(0xFF191C23)
val md_theme_dark_onSurfaceVariant = Color(0xFFEEFCFA)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF2E2E3D)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF9EBBFD)
val md_theme_dark_shadow = Color(0xB0010413)
val md_theme_dark_surfaceTint = Color(0x9223CAF5)
val md_theme_dark_outlineVariant = Color(0xFF9DAFAF)
val md_theme_dark_scrim = Color(0xFF8CB1AB)


val seed = Color(0xFF825500)